Scaffold files should be commited
district09/drupal8_project_template pull request #8
Opened 2018-08-07 07:22 UTC by wesleydv

From https://github.com/drupal-composer/drupal-scaffold
> It is assumed that the scaffold files will be committed to the repository, to ensure that the correct files are used on the CI server (see Limitation, above). After running composer install for the first time commit the scaffold files to your repository.

2018-08-07 09:21 UTC, zero2one approved these changes

2018-08-07 14:33 UTC, daften commented
Wouldn't it be better to try to align with gitignore from the upstream project.
See https://github.com/drupal-composer/drupal-project/blob/8.x/.gitignore

2018-08-07 14:33 UTC, daften requested changes
Wouldn't it be better to try to align with gitignore from the upstream project.
See https://github.com/drupal-composer/drupal-project/blob/8.x/.gitignore

2018-08-14 08:29 UTC, daften commented
Replaced by #9

2018-08-14 08:29 UTC, closed without merging